"""The public workspace and the one-way import of a question from it, on the invented world only.

A repository with planted files is made in a temporary folder by copying the allowlisted public sources and planting
files beside them, so that no test reads anything outside the allowlist of the real repository.
"""
import ast
import csv
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from schemalyser import rolepolicy, workspace

ROOT = workspace.ROOT
DATE = "2026-10-07"
EXAMPLE = f"queries/{workspace.EXAMPLE}"


def _catalogue_names():
    names = set()
    with (ROOT / "fixtures" / "invented-catalogue.csv").open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            names |= {row["TABLE_NAME"], row["COLUMN_NAME"]}
    return {n for n in names if re.fullmatch(r"[A-Z][A-Z0-9]*_[A-Z0-9_]+", n or "")}


@pytest.fixture(scope="module")
def exported(tmp_path_factory):
    out = tmp_path_factory.mktemp("export") / "workspace"
    manifest = workspace.export(out, "public", date=DATE)
    return out, manifest


def _copy_repository(target):
    """A repository that holds the allowlisted public sources and nothing else."""
    for relative in workspace.sources(ROOT):
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(ROOT / relative, destination)
    return target


@pytest.fixture()
def planted(tmp_path):
    repo = _copy_repository(tmp_path / "repo")
    (repo / "reference").mkdir()
    (repo / "reference" / "secret-schema.csv").write_text("PLANTED_REFERENCE_TABLE,PLANTED_REFERENCE_COLUMN\n")
    (repo / "notes").mkdir()
    (repo / "notes" / "plan.md").write_text("PLANTED_NOTE\n")
    (repo / "docs").mkdir()
    (repo / "docs" / "extra.md").write_text("A public page that no allowlist entry names.\n")
    return repo


@pytest.fixture()
def project(tmp_path):
    folder = tmp_path / "hospital-project"
    (folder / "schemas").mkdir(parents=True)
    (folder / "schemas" / "hospital-schema.schemalyser.zip").write_bytes(workspace.invented_schema(ROOT, DATE))
    return folder


def _question_folder(exported, tmp_path, name="low_pressure", sql=None, extra=None):
    out, _ = exported
    folder = tmp_path / "ws" / "queries" / name
    shutil.copytree(out / EXAMPLE, folder)
    if sql is not None:
        (folder / "question.sql").write_text(sql, encoding="utf-8")
    for file_name, text in (extra or {}).items():
        (folder / file_name).write_text(text, encoding="utf-8")
    return folder


def _project_files(project):
    return sorted(p.relative_to(project).as_posix() for p in project.rglob("*") if p.is_file())


# The export.

def test_the_export_holds_the_allowlisted_sources_and_a_manifest_of_every_file(exported):
    out, manifest = exported
    on_disk = sorted(p.relative_to(out).as_posix() for p in out.rglob("*") if p.is_file())
    listed = sorted(f["path"] for f in manifest["files"])
    assert sorted(listed + ["manifest.json"]) == on_disk
    assert manifest["profile"] == "public"
    for entry in manifest["files"]:
        assert entry["sha256"] == workspace.sha256((out / entry["path"]).read_bytes())
        assert not entry["source"].startswith(("/", "reference", "etl")), entry
        assert entry["source"] == "generated by schemalyser.workspace" or (ROOT / entry["source"]).is_file()
    for wanted in ("core/schemalyser/rolemodel/contract.json", "core/schemalyser/rolemodel/roles.md",
                   "core/schemalyser/omop/cdm54_fields.csv", "fixtures/invented-catalogue.csv",
                   "fixtures/dictionary/invented-dictionary.csv", "fixtures/conversion/person.sql", "fixtures/map/map.json",
                   "tools/sqlserver/harness.py", "README.md", "QUERIES.md", f"schemas/{workspace.SCHEMA_NAME}",
                   f"{EXAMPLE}/question.sql", f"{EXAMPLE}/title.txt", f"{EXAMPLE}/note.md"):
        assert wanted in listed, wanted
    assert not any(p.split("/")[0] in ("reference", "etl", "notes", "docs", "site", "spike") for p in on_disk)
    readme = (out / "README.md").read_text(encoding="utf-8")
    assert "cannot see any hospital's mapping from those contracts to its database" in readme
    assert "!" not in readme and "!" not in (out / "QUERIES.md").read_text(encoding="utf-8")


def test_the_core_modules_of_the_allowlist_cover_everything_that_they_import():
    package = ROOT / "core" / "schemalyser"
    held = set(workspace.CORE_MODULES)
    modules = {p.stem for p in package.glob("*.py")}
    for module in workspace.CORE_MODULES:
        tree = ast.parse((package / f"{module}.py").read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.level == 1:
                names = [node.module.split(".")[0]] if node.module else [a.name for a in node.names]
                for name in names:
                    if name in modules:
                        assert name in held, f"{module} imports {name}, which the allowlist leaves out"


def test_a_planted_reference_and_an_unlisted_folder_never_reach_the_workspace(planted, tmp_path):
    out = tmp_path / "out"
    workspace.export(out, "public", repo=planted, date=DATE)
    paths = [p.relative_to(out).as_posix() for p in out.rglob("*") if p.is_file()]
    assert not any(p.startswith(("reference/", "notes/", "docs/")) for p in paths)
    for path in out.rglob("*"):
        if path.is_file():
            assert b"PLANTED_REFERENCE" not in path.read_bytes() and b"PLANTED_NOTE" not in path.read_bytes(), path


def test_a_file_outside_the_allowlist_is_refused_with_its_path_unless_it_is_listed(planted, tmp_path):
    with pytest.raises(workspace.WorkspaceError, match="docs/extra.md"):
        workspace.export(tmp_path / "one", "public", repo=planted, include=["docs/extra.md"], date=DATE)
    listed = workspace.ALLOWLIST + ({"path": "docs/extra.md", "why": "a test"},)
    workspace.export(tmp_path / "two", "public", repo=planted, allowlist=listed, include=["docs/extra.md"], date=DATE)
    assert (tmp_path / "two" / "docs" / "extra.md").is_file()
    denied = workspace.ALLOWLIST + ({"path": "reference/secret-schema.csv", "why": "a test"},)
    with pytest.raises(workspace.WorkspaceError, match="reference/secret-schema.csv"):
        workspace.export(tmp_path / "three", "public", repo=planted, allowlist=denied, date=DATE)
    assert not (tmp_path / "three").exists()


def test_a_file_of_the_wrong_kind_or_a_link_in_an_allowlisted_folder_is_refused(planted, tmp_path):
    (planted / "fixtures" / "conversion" / "minutes.docx").write_bytes(b"x")
    with pytest.raises(workspace.WorkspaceError, match="fixtures/conversion/minutes.docx"):
        workspace.export(tmp_path / "one", "public", repo=planted, date=DATE)
    (planted / "fixtures" / "conversion" / "minutes.docx").unlink()
    (planted / "fixtures" / "map" / "linked.sql").symlink_to(planted / "reference" / "secret-schema.csv")
    with pytest.raises(workspace.WorkspaceError, match="fixtures/map/linked.sql"):
        workspace.export(tmp_path / "two", "public", repo=planted, date=DATE)


def test_text_that_names_a_home_folder_is_refused(planted, tmp_path):
    (planted / "fixtures" / "map" / "role_note.sql").write_text("-- written in /Users/someone/project\n")
    with pytest.raises(workspace.WorkspaceError, match="fixtures/map/role_note.sql"):
        workspace.export(tmp_path / "out", "public", repo=planted, date=DATE)


def test_an_agent_in_the_workspace_can_check_assess_and_build_the_example_on_invented_data(exported, tmp_path):
    out, _ = exported
    work = tmp_path / "copy"
    shutil.copytree(out, work)
    env = dict(os.environ, PYTHONPATH="core", PYTHONDONTWRITEBYTECODE="1")

    def run(*args):
        return subprocess.run([sys.executable, *args], cwd=work, env=env, capture_output=True, text=True, timeout=300)

    found = run("-c", "import schemalyser, schemalyser.testbed; print(schemalyser.__file__)")
    assert found.returncode == 0, found.stderr
    assert Path(found.stdout.strip()).resolve().is_relative_to(work.resolve())
    assert run("-m", "schemalyser.workspace", "check", EXAMPLE).returncode == 0
    schema = f"schemas/{workspace.SCHEMA_NAME}"
    report = run("-m", "schemalyser.feasibility", "report", schema, f"{EXAMPLE}/question.sql")
    assert report.returncode == 0 and "expressible" in report.stdout, report.stderr
    built = run("-m", "schemalyser.audit", "build", schema, f"{EXAMPLE}/question.sql", "--out", "audits/example")
    assert built.returncode == 0, built.stderr
    manifest = json.loads((work / "audits" / "example" / "manifest.json").read_text(encoding="utf-8"))
    assert manifest["execution_class"] == "B" and manifest["planted_match"] is True


# The import.

def test_the_example_imports_cleanly_and_the_result_names_nothing_of_the_hospital(exported, project, tmp_path):
    folder = _question_folder(exported, tmp_path)
    result, _, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "accepted" and result["rules_failed"] == []
    assert sorted(result) == ["query", "result", "rules_failed", "says"]
    assert result["says"] == workspace.WORDING["accepted"]
    text = (folder / "import-result.json").read_text(encoding="utf-8")
    assert json.loads(text) == result
    leaked = [name for name in _catalogue_names() if name in text]
    assert not leaked, leaked
    assert sorted(p.name for p in folder.iterdir()) == ["import-result.json", "note.md", "question.sql", "title.txt"]
    # The private project gains the question, the package and the validation report.
    questions = list((project / "questions").glob("*.sql"))
    assert [q.name for q in questions] == ["neonatal_low_mean_pressure.sql"]
    assert questions[0].read_text(encoding="utf-8").startswith("-- Neonatal low mean pressure.\n")
    assert (record / "package" / "query.sql").is_file() and (record / "package" / "manifest.json").is_file()
    validation = json.loads((record / "import-validation.json").read_text(encoding="utf-8"))
    assert validation["returned_to_workspace"] == result and all(r["passed"] for r in validation["rules"])
    assert json.loads((record / "request.json").read_text(encoding="utf-8"))["exit_code"] == 0


def test_a_question_that_names_a_table_outside_the_contract_is_refused_with_the_rule(exported, project, tmp_path):
    before = _project_files(project)
    folder = _question_folder(exported, tmp_path, sql="SELECT COUNT(*) AS anaesthetics FROM ANAES_RECORD\n")
    result, checked, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "malformed" and result["rules_failed"] == ["tables"] and record is None
    assert sorted(result) == ["query", "result", "rules_failed", "says"]
    assert json.loads((folder / "import-result.json").read_text(encoding="utf-8")) == result
    assert _project_files(project) == before


def test_a_folder_with_an_extra_python_file_is_refused(exported, project, tmp_path):
    before = _project_files(project)
    folder = _question_folder(exported, tmp_path, extra={"helper.py": "import os\n"})
    result, checked, _ = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "malformed" and result["rules_failed"] == ["files"]
    assert any("helper.py" in f for r in checked["rules"] for f in r["fragments"])
    assert _project_files(project) == before


def test_a_link_a_dependency_and_a_large_file_are_each_refused(exported, project, tmp_path):
    folder = _question_folder(exported, tmp_path, name="linked", extra={"requirements.txt": "requests\n"})
    (folder / "note.md").unlink()
    (folder / "note.md").symlink_to(project / "schemas" / "hospital-schema.schemalyser.zip")
    result, _, _ = workspace.import_question(folder, project, date=DATE)
    assert set(result["rules_failed"]) == {"links", "dependencies", "files"}
    large = _question_folder(exported, tmp_path, name="large", sql="-- " + "x" * workspace.SIZE_LIMIT + "\nSELECT 1 AS one\n")
    result, _, _ = workspace.import_question(large, project, date=DATE)
    assert result["rules_failed"] == ["size"]


# The role-level policy.

@pytest.mark.parametrize("sql, rule", [
    ("SELECT x.foo FROM role_anaesthetic x", "columns"),
    ("SELECT COUNT(*) AS n FROM role_reading r WHERE r.kind = 'blood_pressure'", "kinds"),
    ("SELECT UPPER(CAST(p.patient_key AS varchar(20))) AS k FROM role_patient p", "functions"),
    ("SELECT p.patient_key FROM otherdb.dbo.role_patient p", "names"),
    ("EXEC sp_who", "dynamic"),
    ("SELECT 1 AS one; SELECT 2 AS two", "statements"),
    ("SELECT p.patient_key INTO #kept FROM role_patient p", "statements"),
    ("SELECT d.sex FROM role_patient_detail d", "tables"),
    ("WITH c AS (SELECT patient_key FROM role_patient) SELECT c.birth_date FROM c", "columns"),
    ("SELECT * FROM OPENQUERY(other, 'SELECT 1')", "dynamic"),
])
def test_the_role_policy_names_the_rule_that_a_question_breaks(sql, rule):
    found = rolepolicy.check(sql)
    assert found["outcome"] == "failed" and rule in found["failed"], found["failed"]
    assert next(r for r in found["rules"] if r["id"] == rule)["fragments"]


def test_the_role_policy_passes_the_neonatal_audit():
    found = rolepolicy.check((ROOT / workspace.EXAMPLE_SOURCE).read_text(encoding="utf-8"))
    assert found["outcome"] == "passed", [r for r in found["rules"] if not r["passed"]]
