"""The public workspace and the one-way import of a question from it, on the invented world only.

A repository with planted files is made in a temporary folder by copying the allowlisted public sources and planting
files beside them, so that no test reads anything outside the allowlist of the real repository.
"""
import ast
import csv
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from schemalyser import audit, describe, rolemap, rolepolicy, workspace

ROOT = workspace.ROOT
DATE = "2026-10-07"
EXAMPLE = f"queries/{workspace.EXAMPLE}"


def _catalogue_names():
    names = set()
    with (ROOT / "fixtures" / "invented-catalogue.csv").open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            names |= {row["TABLE_NAME"], row["COLUMN_NAME"]}
    return {n for n in names if re.fullmatch(r"[A-Z][A-Z0-9]*_[A-Z0-9_]+", n or "")}


@pytest.fixture(scope="module")
def exported(tmp_path_factory):
    out = tmp_path_factory.mktemp("export") / "workspace"
    manifest = workspace.export(out, "public", date=DATE)
    return out, manifest


def _copy_repository(target):
    """A repository that holds the allowlisted public sources, with the planted neonates from which the export takes
    the planted rows, and nothing else."""
    for relative in list(workspace.sources(ROOT)) + [workspace.PLANTED_NEONATES]:
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(ROOT / relative, destination)
    return target


@pytest.fixture()
def planted(tmp_path):
    repo = _copy_repository(tmp_path / "repo")
    (repo / "reference").mkdir()
    (repo / "reference" / "secret-schema.csv").write_text("PLANTED_REFERENCE_TABLE,PLANTED_REFERENCE_COLUMN\n")
    (repo / "notes").mkdir()
    (repo / "notes" / "plan.md").write_text("PLANTED_NOTE\n")
    (repo / "docs").mkdir()
    (repo / "docs" / "extra.md").write_text("A public page that no allowlist entry names.\n")
    return repo


@pytest.fixture()
def project(tmp_path):
    folder = tmp_path / "hospital-project"
    (folder / "schemas").mkdir(parents=True)
    (folder / "schemas" / "hospital-schema.schemalyser.zip").write_bytes(workspace.invented_schema(ROOT, DATE))
    return folder


def _question_folder(exported, tmp_path, name="low_pressure", sql=None, extra=None):
    out, _ = exported
    folder = tmp_path / "ws" / "queries" / name
    shutil.copytree(out / EXAMPLE, folder)
    if sql is not None:
        (folder / "question.sql").write_text(sql, encoding="utf-8")
    for file_name, text in (extra or {}).items():
        (folder / file_name).write_text(text, encoding="utf-8")
    return folder


def _project_files(project):
    return sorted(p.relative_to(project).as_posix() for p in project.rglob("*") if p.is_file())


# The export.

def test_the_export_holds_the_allowlisted_sources_and_a_manifest_of_every_file(exported):
    out, manifest = exported
    on_disk = sorted(p.relative_to(out).as_posix() for p in out.rglob("*") if p.is_file())
    listed = sorted(f["path"] for f in manifest["files"])
    assert sorted(listed + ["manifest.json"]) == on_disk
    assert manifest["profile"] == "public"
    for entry in manifest["files"]:
        assert entry["sha256"] == workspace.sha256((out / entry["path"]).read_bytes())
        assert not entry["source"].startswith(("/", "reference", "etl")), entry
        assert entry["source"] == "generated by schemalyser.workspace" or (ROOT / entry["source"]).is_file()
    for wanted in ("core/schemalyser/rolemodel/contract.json", "core/schemalyser/rolemodel/roles.md",
                   "core/schemalyser/omop/cdm54_fields.csv", "fixtures/invented-catalogue.csv",
                   "fixtures/dictionary/invented-dictionary.csv", "fixtures/conversion/person.sql", "fixtures/map/map.json",
                   "tools/sqlserver/harness.py", "README.md", "QUERIES.md", f"schemas/{workspace.SCHEMA_NAME}",
                   f"{EXAMPLE}/question.sql", f"{EXAMPLE}/title.txt", f"{EXAMPLE}/note.md"):
        assert wanted in listed, wanted
    assert not any(p.split("/")[0] in ("reference", "etl", "notes", "docs", "site", "spike") for p in on_disk)
    readme = (out / "README.md").read_text(encoding="utf-8")
    assert "cannot see any hospital's mapping from those contracts to its database" in readme
    assert "!" not in readme and "!" not in (out / "QUERIES.md").read_text(encoding="utf-8")


def test_the_core_modules_of_the_allowlist_cover_everything_that_they_import():
    package = ROOT / "core" / "schemalyser"
    held = set(workspace.CORE_MODULES)
    modules = {p.stem for p in package.glob("*.py")}
    for module in workspace.CORE_MODULES:
        tree = ast.parse((package / f"{module}.py").read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.level == 1:
                names = [node.module.split(".")[0]] if node.module else [a.name for a in node.names]
                for name in names:
                    if name in modules:
                        assert name in held, f"{module} imports {name}, which the allowlist leaves out"


def test_a_planted_reference_and_an_unlisted_folder_never_reach_the_workspace(planted, tmp_path):
    out = tmp_path / "out"
    workspace.export(out, "public", repo=planted, date=DATE)
    paths = [p.relative_to(out).as_posix() for p in out.rglob("*") if p.is_file()]
    assert not any(p.startswith(("reference/", "notes/", "docs/")) for p in paths)
    for path in out.rglob("*"):
        if path.is_file():
            assert b"PLANTED_REFERENCE" not in path.read_bytes() and b"PLANTED_NOTE" not in path.read_bytes(), path


def test_a_file_outside_the_allowlist_is_refused_with_its_path_unless_it_is_listed(planted, tmp_path):
    with pytest.raises(workspace.WorkspaceError, match="docs/extra.md"):
        workspace.export(tmp_path / "one", "public", repo=planted, include=["docs/extra.md"], date=DATE)
    listed = workspace.ALLOWLIST + ({"path": "docs/extra.md", "why": "a test"},)
    workspace.export(tmp_path / "two", "public", repo=planted, allowlist=listed, include=["docs/extra.md"], date=DATE)
    assert (tmp_path / "two" / "docs" / "extra.md").is_file()
    denied = workspace.ALLOWLIST + ({"path": "reference/secret-schema.csv", "why": "a test"},)
    with pytest.raises(workspace.WorkspaceError, match="reference/secret-schema.csv"):
        workspace.export(tmp_path / "three", "public", repo=planted, allowlist=denied, date=DATE)
    assert not (tmp_path / "three").exists()


def test_a_file_of_the_wrong_kind_or_a_link_in_an_allowlisted_folder_is_refused(planted, tmp_path):
    (planted / "fixtures" / "conversion" / "minutes.docx").write_bytes(b"x")
    with pytest.raises(workspace.WorkspaceError, match="fixtures/conversion/minutes.docx"):
        workspace.export(tmp_path / "one", "public", repo=planted, date=DATE)
    (planted / "fixtures" / "conversion" / "minutes.docx").unlink()
    (planted / "fixtures" / "map" / "linked.sql").symlink_to(planted / "reference" / "secret-schema.csv")
    with pytest.raises(workspace.WorkspaceError, match="fixtures/map/linked.sql"):
        workspace.export(tmp_path / "two", "public", repo=planted, date=DATE)


def test_text_that_names_a_home_folder_is_refused(planted, tmp_path):
    (planted / "fixtures" / "map" / "role_note.sql").write_text("-- written in /Users/someone/project\n")
    with pytest.raises(workspace.WorkspaceError, match="fixtures/map/role_note.sql"):
        workspace.export(tmp_path / "out", "public", repo=planted, date=DATE)


def test_an_agent_in_the_workspace_can_check_assess_and_build_the_example_on_invented_data(exported, tmp_path):
    out, _ = exported
    work = tmp_path / "copy"
    shutil.copytree(out, work)
    env = dict(os.environ, PYTHONPATH="core", PYTHONDONTWRITEBYTECODE="1")

    def run(*args):
        return subprocess.run([sys.executable, *args], cwd=work, env=env, capture_output=True, text=True, timeout=300)

    found = run("-c", "import schemalyser, schemalyser.testbed; print(schemalyser.__file__)")
    assert found.returncode == 0, found.stderr
    assert Path(found.stdout.strip()).resolve().is_relative_to(work.resolve())
    assert run("-m", "schemalyser.workspace", "check", EXAMPLE).returncode == 0
    schema = f"schemas/{workspace.SCHEMA_NAME}"
    report = run("-m", "schemalyser.feasibility", "report", schema, f"{EXAMPLE}/question.sql")
    assert report.returncode == 0 and "expressible" in report.stdout, report.stderr
    built = run("-m", "schemalyser.audit", "build", schema, f"{EXAMPLE}/question.sql", "--out", "audits/example")
    assert built.returncode == 0, built.stderr
    manifest = json.loads((work / "audits" / "example" / "manifest.json").read_text(encoding="utf-8"))
    # The planted neonates' expected answers are held out, so the workspace's package checks no planted case.
    assert manifest["execution_class"] == "B" and manifest["planted_match"] is None


# The import.

def test_the_example_imports_cleanly_and_the_result_names_nothing_of_the_hospital(exported, project, tmp_path):
    folder = _question_folder(exported, tmp_path)
    result, _, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "accepted" and result["rules_failed"] == []
    assert sorted(result) == ["query", "result", "rules_failed", "says"]
    assert result["says"] == workspace.WORDING["accepted"]
    text = (folder / "import-result.json").read_text(encoding="utf-8")
    assert json.loads(text) == result
    leaked = [name for name in _catalogue_names() if name in text]
    assert not leaked, leaked
    assert sorted(p.name for p in folder.iterdir()) == ["import-result.json", "note.md", "question.sql", "title.txt"]
    # The private project gains the question, the package and the validation report.
    questions = list((project / "questions").glob("*.sql"))
    assert [q.name for q in questions] == ["neonatal_low_mean_pressure.sql"]
    assert questions[0].read_text(encoding="utf-8").startswith("-- Neonatal low mean pressure.\n")
    assert (record / "package" / "query.sql").is_file() and (record / "package" / "manifest.json").is_file()
    validation = json.loads((record / "import-validation.json").read_text(encoding="utf-8"))
    assert validation["returned_to_workspace"] == result and all(r["passed"] for r in validation["rules"])
    assert json.loads((record / "request.json").read_text(encoding="utf-8"))["exit_code"] == 0


def test_a_question_that_names_a_table_outside_the_contract_is_refused_with_the_rule(exported, project, tmp_path):
    before = _project_files(project)
    folder = _question_folder(exported, tmp_path, sql="SELECT COUNT(*) AS anaesthetics FROM ANAES_RECORD\n")
    result, checked, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "malformed" and result["rules_failed"] == ["tables"] and record is None
    assert sorted(result) == ["query", "result", "rules_failed", "says"]
    assert json.loads((folder / "import-result.json").read_text(encoding="utf-8")) == result
    assert _project_files(project) == before


def test_a_folder_with_an_extra_python_file_is_refused(exported, project, tmp_path):
    before = _project_files(project)
    folder = _question_folder(exported, tmp_path, extra={"helper.py": "import os\n"})
    result, checked, _ = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "malformed" and result["rules_failed"] == ["files"]
    assert any("helper.py" in f for r in checked["rules"] for f in r["fragments"])
    assert _project_files(project) == before


def test_a_link_a_dependency_and_a_large_file_are_each_refused(exported, project, tmp_path):
    folder = _question_folder(exported, tmp_path, name="linked", extra={"requirements.txt": "requests\n"})
    (folder / "note.md").unlink()
    (folder / "note.md").symlink_to(project / "schemas" / "hospital-schema.schemalyser.zip")
    result, _, _ = workspace.import_question(folder, project, date=DATE)
    assert set(result["rules_failed"]) == {"links", "dependencies", "files"}
    large = _question_folder(exported, tmp_path, name="large", sql="-- " + "x" * workspace.SIZE_LIMIT + "\nSELECT 1 AS one\n")
    result, _, _ = workspace.import_question(large, project, date=DATE)
    assert result["rules_failed"] == ["size"]


# The role-level policy.

@pytest.mark.parametrize("sql, rule", [
    ("SELECT x.foo FROM role_anaesthetic x", "columns"),
    ("SELECT COUNT(*) AS n FROM role_reading r WHERE r.kind = 'blood_pressure'", "kinds"),
    ("SELECT UPPER(CAST(p.patient_key AS varchar(20))) AS k FROM role_patient p", "functions"),
    ("SELECT p.patient_key FROM otherdb.dbo.role_patient p", "names"),
    ("EXEC sp_who", "dynamic"),
    ("SELECT 1 AS one; SELECT 2 AS two", "statements"),
    ("SELECT p.patient_key INTO #kept FROM role_patient p", "statements"),
    ("SELECT d.sex FROM role_patient_detail d", "tables"),
    ("WITH c AS (SELECT patient_key FROM role_patient) SELECT c.birth_date FROM c", "columns"),
    ("SELECT * FROM OPENQUERY(other, 'SELECT 1')", "dynamic"),
])
def test_the_role_policy_names_the_rule_that_a_question_breaks(sql, rule):
    found = rolepolicy.check(sql)
    assert found["outcome"] == "failed" and rule in found["failed"], found["failed"]
    assert next(r for r in found["rules"] if r["id"] == rule)["fragments"]


def test_the_role_policy_passes_the_neonatal_audit():
    found = rolepolicy.check((ROOT / workspace.EXAMPLE_SOURCE).read_text(encoding="utf-8"))
    assert found["outcome"] == "passed", [r for r in found["rules"] if not r["passed"]]


def test_the_role_policy_lets_a_question_read_a_mapping_view_and_checks_the_capabilities_it_names():
    reads = ("-- capability: principal_diagnosis\n"
             "SELECT m.status, COUNT(*) AS n FROM role_anaesthetic a JOIN map_diagnosis_concept m ON m.local_key = a.anaesthetic_key "
             "WHERE m.status IN ('mapped', 'ambiguous') GROUP BY m.status")
    assert rolepolicy.check(reads)["outcome"] == "passed"
    assert rolepolicy.check(reads.replace("'ambiguous'", "'guessed'"))["failed"] == ["kinds"]
    assert rolepolicy.check(reads.replace("m.status,", "m.code,").replace("BY m.status", "BY m.code"))["failed"] == ["columns"]
    unknown = rolepolicy.check("-- capability: minutes_of_unicorns\nSELECT a.anaesthetic_key FROM role_anaesthetic a")
    assert unknown["failed"] == ["capabilities"]
    # A draft part stays closed to a question, whatever capability it names.
    assert "tables" in rolepolicy.check("-- capability: transfusion\nSELECT f.volume_ml FROM role_fluid f")["failed"]


def test_the_export_holds_the_mapping_views_and_the_catalogue_and_no_hospital_s_translation(exported):
    out, _ = exported
    model = json.loads((out / "core/schemalyser/rolemodel/contract.json").read_text(encoding="utf-8"))
    assert model["version"] == "1.1" and model["mapping_views"] and model["capabilities"]
    assert (out / "core/schemalyser/rolemodel/planted_concepts.json").is_file()
    queries = (out / "QUERIES.md").read_text(encoding="utf-8")
    assert "map_drug_concept" in queries and "-- capability: NAME" in queries and "fifteen further views" in queries
    # The invented schema in the workspace holds no translation of codes.
    import zipfile
    with zipfile.ZipFile(out / "schemas" / workspace.SCHEMA_NAME) as archive:
        assert "concepts" not in json.loads(archive.read("map/map.json"))
    # The invented map holds the translations of the invented world's own codes, under a salt that names the invented
    # hospital. Both are invented, so they belong to the public class of material and are exported; nothing else
    # exported carries a salt.
    salted = sorted(p.relative_to(out).as_posix() for p in out.rglob("*.json") if b'"salt"' in p.read_bytes())
    assert salted == ["fixtures/map/map.json"]
    invented = json.loads((out / "fixtures/map/map.json").read_text(encoding="utf-8"))
    assert invented["world"] == "the invented world" and invented["concepts"]["salt"] == "the invented hospital"


def test_a_real_schema_s_translations_never_reach_an_export(planted, tmp_path):
    """A map with translations and a salt that a hospital would hold is refused wherever it is planted: outside the
    allowlist by its path, and inside an allowlisted folder as a saved schema, which that folder may not hold."""
    secret = {"world": "QUARTERMAINE_HOSPITAL", "concepts": {"salt": "QUARTERMAINE_SALT", "views": {"map_drug_concept": {"rows": [
        {"code": "QUARTERMAINE_CODE", "description": "QUARTERMAINE_DESCRIPTION", "concept_id": 1, "status": "mapped"}]}}}}
    held = planted / "reference" / "hospital" / "map"
    held.mkdir(parents=True)
    (held / "map.json").write_text(json.dumps(secret), encoding="utf-8")
    with pytest.raises(workspace.WorkspaceError, match="reference/hospital/map/map.json"):
        workspace.export(tmp_path / "named", "public", repo=planted, include=["reference/hospital/map/map.json"], date=DATE)
    import io
    import zipfile
    schema = io.BytesIO()
    with zipfile.ZipFile(schema, "w") as archive:
        archive.writestr("map/map.json", json.dumps(secret))
    (planted / "fixtures" / "map" / "hospital-schema.schemalyser.zip").write_bytes(schema.getvalue())
    with pytest.raises(workspace.WorkspaceError, match="fixtures/map/hospital-schema.schemalyser.zip"):
        workspace.export(tmp_path / "inside", "public", repo=planted, date=DATE)
    (planted / "fixtures" / "map" / "hospital-schema.schemalyser.zip").unlink()
    out = tmp_path / "clean"
    workspace.export(out, "public", repo=planted, date=DATE)
    for path in out.rglob("*"):
        if path.is_file():
            assert b"QUARTERMAINE" not in path.read_bytes(), path



# The held-out fixtures never reach an export (A26).

def test_the_held_out_fixtures_the_planted_answers_and_the_planted_values_never_reach_an_export(exported, planted, tmp_path):
    out, manifest = exported
    listed = {f["path"] for f in manifest["files"]}
    assert "fixtures/planted-values.txt" not in listed and not any(p.startswith("fixtures/held-out") for p in listed)
    neonates = json.loads((out / workspace.PLANTED_NEONATES).read_text(encoding="utf-8"))
    assert "expectations" not in neonates and neonates["role_reading"]["rows"]
    entry = next(f for f in manifest["files"] if f["path"] == workspace.PLANTED_NEONATES)
    assert entry["source"] == "generated by schemalyser.workspace"
    # The planted inputs that are development fixtures stay.
    assert "fixtures/hospital/OBS_READING.csv" in listed or any(p.startswith("fixtures/hospital/") for p in listed)
    # A marker planted under fixtures/held-out is passed over inside an allowlisted folder and refused when named.
    held = planted / "fixtures" / "held-out" / "neonatal"
    held.mkdir(parents=True)
    (held / "expected.json").write_text('{"marker": "PLANTED_HELD_OUT"}\n')
    (planted / "fixtures" / "planted-values.txt").write_text("PLANTED_VALUE_NAME\n")
    wide = workspace.ALLOWLIST + ({"path": "fixtures", "tree": True, "suffixes": (".json", ".csv", ".sql", ".txt", ".tsv", ".py"),
                                   "why": "a test"},)
    first = tmp_path / "wide"
    workspace.export(first, "public", repo=planted, allowlist=wide, date=DATE)
    for path in first.rglob("*"):
        if path.is_file():
            data = path.read_bytes()
            assert b"PLANTED_HELD_OUT" not in data and b"PLANTED_VALUE_NAME" not in data, path
            assert b'"expectations"' not in data or path.name != "planted_neonates.json", path
    assert not (first / "fixtures" / "held-out").exists() and not (first / "fixtures" / "planted-values.txt").exists()
    for named in ("fixtures/held-out/neonatal/expected.json", "fixtures/held-out", "fixtures/planted-values.txt"):
        entry = {"path": named, "why": "a test"} if not named.endswith("held-out") else {"path": named, "tree": True, "suffixes": (".json",), "why": "a test"}
        with pytest.raises(workspace.WorkspaceError, match=re.escape(named)):
            workspace.export(tmp_path / "named", "public", repo=planted, allowlist=workspace.ALLOWLIST + (entry,), date=DATE)
        with pytest.raises(workspace.WorkspaceError, match=re.escape(named)):
            workspace.export(tmp_path / "included", "public", repo=planted, include=[named], date=DATE)


# The import's small refusals (A27).

def test_a_file_with_the_executable_bit_is_refused(exported, project, tmp_path):
    before = _project_files(project)
    folder = _question_folder(exported, tmp_path, name="executable")
    (folder / "note.md").chmod(0o755)
    result, checked, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "malformed" and result["rules_failed"] == ["executable"] and record is None
    assert any("note.md is executable" in f for r in checked["rules"] for f in r["fragments"])
    assert _project_files(project) == before


# The status depends on the package and the public contract alone (A7).

def _schema_without_the_readings_link(path):
    """A saved schema of the invented world in which the readings are not linked to an anaesthetic, so that no
    package of the neonatal audit can be built from it."""
    fixtures = ROOT / "fixtures"
    sitting = describe.Describe()
    sitting.version = "test"
    sitting.load_dictionary((fixtures / "dictionary" / "invented-dictionary.csv").read_bytes(),
                            (fixtures / "dictionary" / "invented-tables.csv").read_bytes(), {},
                            "invented-dictionary.csv", "invented-tables.csv")
    sitting.propose(date=DATE)
    sitting.set_settings("production", 2024, "Australia/Sydney", True)
    sitting.tables_query()
    sitting.read_tables(workspace._tables_result(fixtures / "invented-catalogue.csv"))
    for about in workspace.CONFIRMED:
        if not about.startswith("role_reading"):
            sitting.confirm(about, "yes", date=DATE)
    sitting.data["roles"]["role_reading"]["columns"]["anaesthetic_key"]["binding"] = None
    path.write_bytes(sitting.save_zip(DATE))
    return path


ROW_LEVEL = ("WITH chosen AS (SELECT a.anaesthetic_key, a.start_time FROM role_anaesthetic a)\n"
             "SELECT c.anaesthetic_key, r.value FROM chosen c JOIN role_reading r ON r.anaesthetic_key = c.anaesthetic_key\n")


@pytest.mark.parametrize("sql, status", [(None, "accepted"), (ROW_LEVEL, "requires_private_review")])
def test_one_package_returns_the_same_status_from_a_hospital_that_supports_it_and_one_that_does_not(
        exported, project, tmp_path, sql, status):
    without = tmp_path / "without-project"
    (without / "schemas").mkdir(parents=True)
    _schema_without_the_readings_link(without / "schemas" / "hospital-schema.schemalyser.zip")
    results, records = [], []
    for name, hospital in (("supports", project), ("lacks", without)):
        folder = _question_folder(exported, tmp_path / name, sql=sql)
        result, _, record = workspace.import_question(folder, hospital, date=DATE)
        results.append(result)
        records.append(json.loads((record / "import-validation.json").read_text(encoding="utf-8")))
        assert (folder / "import-result.json").read_text(encoding="utf-8") == json.dumps(result, indent=2) + "\n"
    assert results[0] == results[1] and results[0]["result"] == status
    if sql is None:
        # The private build differs between the two hospitals, and only the owner's report says so.
        assert records[0]["package"] == "package" and records[1]["package"] is None
        assert records[1]["build_failure"]["error"] == "AuditError"


@pytest.mark.parametrize("sql", [None, ROW_LEVEL, "SELECT COUNT(*) AS anaesthetics FROM ANAES_RECORD\n"])
def test_the_workspace_s_own_check_gives_the_status_that_the_import_returns(exported, project, tmp_path, sql):
    folder = _question_folder(exported, tmp_path, sql=sql)
    checked = workspace.check_folder(folder)
    result, _, _ = workspace.import_question(folder, project, date=DATE)
    assert checked["status"] == result["result"]


def test_a_question_that_provokes_an_error_in_the_private_build_returns_only_its_status(exported, project, tmp_path):
    # A question that passes every public rule but has no step from which part 2 could reach the readings.
    sql = "SELECT COUNT(*) AS readings FROM role_reading r WHERE r.kind = 'map_arterial'\n"
    folder = _question_folder(exported, tmp_path, sql=sql)
    result, _, record = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == "requires_private_review" and sorted(result) == ["query", "result", "rules_failed", "says"]
    text = (folder / "import-result.json").read_text(encoding="utf-8")
    assert "Schemalyser cannot" not in text and "OBS_" not in text and str(project) not in text
    validation = json.loads((record / "import-validation.json").read_text(encoding="utf-8"))
    assert validation["build_failure"] is not None and validation["public_form"] == ["cohort"]


# Carried from the earlier boundary's tests (B8). What they protected now lives in the import: a hostile question puts
# nothing of its own into what returns to the workspace, and neither the module nor an import opens a network module.

HOSTILE = """-- Zanzibarine note: Quartermaine asked for this, and the result goes to xylophonist@example.com.
"""
HOSTILE_WORDS = ("zanzibarine", "xylophonist", "quartermaine")


def _returned_words(text):
    """The words of import-result.json that are not the import's own: its fields, statuses, rules and wording."""
    own = set(workspace.RESULT_FIELDS) | set(workspace.RESULTS) | set(workspace.FOLDER_RULES)
    own |= {r["id"] for r in rolepolicy.check("SELECT 1")["rules"]}
    for sentence in workspace.WORDING.values():
        own |= set(re.findall(r"[A-Za-z_]+", sentence))
    return {w for w in re.findall(r"[A-Za-z_]+", text) if w not in own}


@pytest.mark.parametrize("hostile", ["comments", "tables", "files"])
def test_a_hostile_question_puts_nothing_of_its_own_into_what_returns_to_the_workspace(exported, project, tmp_path, hostile):
    out, _ = exported
    sql = (out / EXAMPLE / "question.sql").read_text(encoding="utf-8")
    extra = {}
    if hostile == "comments":
        # A question that passes every rule, with hostile words in its comment, its title and its note.
        sql = HOSTILE + sql
        extra = {"title.txt": "Zanzibarine Xylophonist\n", "note.md": "Quartermaine wrote this for Xylophonist.\n"}
    elif hostile == "tables":
        sql = HOSTILE + ("SELECT 'Zanzibarine' AS Xylophonist, z.Quartermaine FROM Zanzibarine_Table AS z;\n"
                         "EXEC('SELECT * FROM Zanzibarine_Secret');\n")
    else:
        extra = {"Zanzibarine.sql": "SELECT 1 AS Xylophonist\n", "requirements.txt": "quartermaine\n"}
    folder = _question_folder(exported, tmp_path, sql=sql, extra=extra)
    before = sorted(p.name for p in folder.iterdir())
    result, _, _ = workspace.import_question(folder, project, date=DATE)
    assert result["result"] == ("accepted" if hostile == "comments" else "malformed")
    text = (folder / workspace.RESULT).read_text(encoding="utf-8")
    assert not [word for word in HOSTILE_WORDS if word in text.lower()]
    # The one word that is not the import's own is the folder's name, which the agent chose.
    assert _returned_words(text) == {"low_pressure"}
    # Nothing returns to the workspace but import-result.json.
    assert sorted(p.name for p in folder.iterdir()) == sorted(before + [workspace.RESULT])


def test_the_module_and_an_import_open_no_network_module(exported, project, tmp_path):
    # What the interpreter and the parser import is not the tool's doing: on Linux, sqlglot reads its own version
    # through a standard module that pulls in the email package, which imports socket without opening a connection.
    # So only what the import adds beyond its dependency is counted.
    folder = _question_folder(exported, tmp_path)
    code = (
        "import sys\n"
        "network = ('socket', 'ssl', 'http.client', 'urllib.request', 'urllib3', 'requests', 'httpx')\n"
        "import sqlglot\n"
        "at_start = {m for m in network if m in sys.modules}\n"
        "import schemalyser.workspace as w\n"
        "assert 'duckdb' not in sys.modules, 'duckdb at import'\n"
        f"assert w.check_folder({str(folder)!r})['status'] == 'accepted'\n"
        f"result, _, _ = w.import_question({str(folder)!r}, {str(project)!r}, date={DATE!r})\n"
        "assert result['result'] == 'accepted', result\n"
        "print(sorted(m for m in network if m in sys.modules and m not in at_start))\n"
    )
    done = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True, cwd=ROOT / "core",
                          env={**os.environ, "PYTHONPATH": str(ROOT / "core")}, timeout=300)
    assert done.returncode == 0, done.stderr
    assert done.stdout.strip().splitlines()[-1] == "[]"
